### PR TITLE
eXquilla patch

### PR DESCRIPTION
**Pull request by vaderf**
This patch allows to list and reorder eXquilla type account. This will solve issue #46.

### CODE REVIEW

**Comment by protz** [comment]
Thanks. This looks legit and I believe you've confirmed that it works? (I don't have Exquilla). I'll do another release for this.

**Comment by vaderf** [comment]
Yes, it works (sorry to not have mentioned it). I am currently using the add-on with this modification and successfully modified order of eXquilla accounts. By the way, thank you for maintaining this add-on.

**Comment by mjolnirgs** [comment]
There seems to be a regression for this patch. My eXquilla was updated this morning to ver 68.1.1 and now I cannot move my eXquilla account from the bottom of the folder list, either by manually editing prefs.js, using about:config or by using the Manually sort folders extension

I am using Thunderbird 68.2.2 on Kubuntu 18.04. 

and also Thank you for maintaining this add on

**Comment by vaderf** [comment]
Hello everyone.

I don't use eXquilla anymore as it is back to a closed source model with fee. So I won't be able to help on this anymore. For what it's worth, I have switched to [Provider for Exchange ActiveSync](https://github.com/jobisoft/EAS-4-TbSync/wiki/About:-Provider-for-Exchange-ActiveSync).

**Pull request merged**
