### PR TITLE
Prevent list out of screen

### PR DESCRIPTION
**Pull request by bellingeri**
With many email accounts the window becomes unmanageable because it can exit the from screen.
This change limits the window to a maximum height of 800 pixels.

### CODE REVIEW

**Comment by bellingeri** [comment]
You're absolutely right.
I don't know how to specify the style: it seems that "100vh" doesn't work.

**Comment by jtagcat** [comment]
> You're absolutely right.
> I don't know how to specify the style: it seems that "100vh" doesn't work.

There are [many units](https://www.w3schools.com/CSSref/css_units.asp), I'd try `%`.

**Comment by bellingeri** [comment]
Forgive me, but I have tried "many units" without success.
Setting a static values was the best I managed to achieve.
I pray who is better than me to provide... In between, this setting allows you to use the window.

**Comment by jtagcat** [comment]
I'm not an expert neither, I guess static units will do, until someone complains.

You might want to ask on the add-ons channels on [Mozilla Matrix](https://chat.mozilla.org/).

**Comment by protz** [comment]
@itagagaki do you have thoughts on this PR?

**Comment by itagagaki** [comment]
> @itagagaki do you have thoughts on this PR?

Hmmm, I'm not sure.
I'll think about it when I get some time.

**Comment by itagagaki** [comment]
I have found and implemented an alternative solution.
Please check it out.
https://github.com/protz/Manually-Sort-Folders/pull/129

**Comment by protz** [comment]
Closing this since @itagagaki has provided a fix.

**Pull request closed without merging**
