### PR TITLE
Feature release tb68

### PR DESCRIPTION
**Pull request by Ximi1970**
HI @protz,

I made these changes a few months ago to make the plugin compatible with the newer TBs. Now 68 is out, it is time to release the patches.
Wanted to pass them to you a long time ago but have had the time to do it.

Have a look, thank you.

### CODE REVIEW

**Comment by htgoebel** [comment]
I can confirm this pull-request works for me. I had to restart Thunderbird twice, though,

**Comment by cpharlok** [comment]
> I can confirm this pull-request works for me. I had to restart Thunderbird twice, though,

Can you please check if you can put Local Folders at first place, before accounts?

**Comment by htgoebel** [comment]
> Can you please check if you can put Local Folders at first place, before accounts?

Not sure what you mean. But: Setting "First Account" to "Local Folders" on the "Sort Accounts" tab, local folders are still displayed below the regular Mail-Accounts.

Anyway, even if not all functions are yet working, I'd suggest merging this pull-reqest since it enables Sort Folders for TB 68. (Maybe after cleaning it up, thus the history is less consusing whan looking at it in 10 years time.)

**Comment by cpharlok** [comment]
> > Can you please check if you can put Local Folders at first place, before accounts?
> 
> Not sure what you mean. But: Setting "First Account" to "Local Folders" on the "Sort Accounts" tab, local folders are still displayed below the regular Mail-Accounts.
> 
Yes, that was I needed to know, thank you (so it is not my tb configuration). Seems tb68 changed that because I can't put Local Folders first even touching the advanced configuration, something that could be done in earlier versions.

**Comment by protz** [comment]
Thanks @Ximi1970. Looking now

**Comment by protz** [comment]
I'm getting `tbsortfolders.Logging.LogMod.Formatter is undefined`... looking further.

**Comment by protz** [comment]
I couldn't get the logging infrastructure to work locally, so I just dropped that custom module in favor of reusing the default Log module from Thunderbird. Since we're dropping pre-68 compatibility, I also removed a couple codepaths (on my 68 installation the code was systematically trying to load the wrong MailUtils with a NS_FILE_NOT_FOUND error so I gave up on that too).

I had to restart Thunderbird a couple times to get it work fine, but now I don't see to witness any issues. I've uploaded a build which I will now proceed to upload on addons.mozilla.org -- note that it seems that making local folders the default account to force it to appear first in the list appears to have been broken a while ago.

Note that this is broken already on Thunderbird Beta (70).

Huge thanks for submitting those fixes -- much appreciated!

**Comment by Ximi1970** [comment]
Great !! Thanks for fixing the last problems. I saw the latest issues after the pre-release but did not have the time yet  to check/solve them myself...

**Pull request merged**
