### PR TITLE
Update locales

### PR DESCRIPTION
**Pull request by htgoebel**
* Update German locale.
    Change wording to be more pleasing.

* Remove promotional texts for GMail from translations.
    
    Gmail is a proprietary, commercial service and a open source tool
    should not promote it. Thus I removed all references to this service
    from the translations I was able to decipher. For some of the
    languages the grammar might not be perfect now.

### CODE REVIEW

**Comment by htgoebel** [comment]
@protz Anything to be improved to get this pull-request merged??

**Comment by itagagaki** [comment]
I have recently become a collaborator on this product.
I would like to process this PR as it seems to have been neglected.

I'd like to review the improvement of the German locale and the things about Gmail separately.

@htgoebel Can you please just PR the improvement of the German locale first?
There are conflicts now as shown below.
https://github.com/protz/Manually-Sort-Folders/pull/90/conflicts

The first step is to create a PR that solves this conflict and only improves the German locale.

The second step is.. I don't understand the nuances of the German language, so I would like someone else who understands the nuances of the German language to review the changes.

I suggest that we discuss the things about Gmail after the above is done.

**Comment by htgoebel** [comment]
> @htgoebel Can you please just PR the improvement of the German locale first?

done

> so I would like someone else who understands the nuances of the German language to review the changes.

Well, I'm a native speaker and technical writer.I think this should be enough as a proof, shouldn't it?

**Comment by itagagaki** [comment]
Thank you for your work.
I'm sorry if I offended you. It's not that I don't trust your work. It is better to have a different person review the program code and documentation before merging it.

**Comment by msprotz** [comment]
The patch as it currently stands looks good to me! Thanks @itagagaki for taking care of this PR I unfortunately neglected.

**Comment by htgoebel** [comment]
@itagagaki @msprotz pinging

**Comment by msprotz** [comment]
@itagagaki I think this is ok to merge as-is since it only affects the German locale... what do you think?

**Comment by itagagaki** [comment]
Yes, I don't see any problems with it.
@htgoebel I'm sorry for putting you on hold for so long.

**Comment by msprotz** [comment]
@itagagaki I'll let you merge then... thanks for taking a look!

**Comment by itagagaki** [comment]
@htgoebel Thank you for your contribution. I have merged it.
I would like to discuss with @protz about the next release, but I think it would be better to release it when some bugs are fixed or some features are added.
Until then, you can download and use the code from the merged repository if you like 🙂

**Pull request merged**
