### PR TITLE
Fix #140 not working on thunderbird verstion 86.0b1

### LINKED ISSUE #140: not working on thunderbird verstion 86.0b1
not working on thunderbird verstion 86.0b1

### PR DESCRIPTION
**Pull request by blono**
The original code for the fix can be found at
https://github.com/thundernest/addon-developer-support/blob/master/wrapper-apis/WindowListener/implementation.js

### CODE REVIEW

**Comment by jobisoft** [comment]
Please update the PR to include a full 1-to-1 copy of the WindowListener API files from here:
https://github.com/thundernest/addon-developer-support/tree/master/wrapper-apis/WindowListener

Unofficial versions might not make it thru add-on review, to ensure compatibility with other add-ons.

**Comment by blono** [comment]
Affirmative!

**Comment by blono** [comment]
The entire WindowListener has been updated to the latest version.
Thunderbird 86.0b2 has been confirmed to work.

**Comment by protz** [comment]
This looks good to me (except for the typo, `localicedXulString`?). I would be happy to get @itagagaki's opinion!

**Comment by blono** [comment]
Updated WindowListener to the latest version.
I've also fixed the typo in localicedXulString.
Thunderbird 86.0b3 has been confirmed to work.

**Comment by itagagaki** [comment]
It looks good from a quick look.
I'll also try to check it works with TB86.0b3 and merge it if it looks OK.

**Pull request merged**
